### ISSUE TITLE
trait bound `D: std::clone::Clone` is not satisfied

### ISSUE THREAD

**Issue by cteters** [timvisee/qr2term-rs#6] opened 2019-07-26 05:25 UTC
Hi Time, I received the following error message when trying to build the crate:

error[E0277]: the trait bound `D: std::clone::Clone` is not satisfied
   --> /home/tango/.cargo/registry/src/github.com-1ecc6299db9ec823/crossterm-0.9.6/src/crossterm.rs:95:5
    |
95  | /     pub fn style<D>(&self, val: D) -> crossterm_style::StyledObject<D>
96  | |     where
97  | |         D: Display,
98  | |     {
99  | |         crossterm_style::ObjectStyle::new().apply_to(val)
100 | |     }
    | |_____^ the trait `std::clone::Clone` is not implemented for `D`
    |
    = help: consider adding a `where D: std::clone::Clone` bound
    = note: required by `crossterm_style::StyledObject`

**Comment by timvisee** [comment] 2019-07-26 08:06
Weird. What Rust version are you using?

I'll attempt to debug this soon. It might be caused by a breaking change in one of the dependencies.

**Comment by timvisee** [comment] 2019-07-26 10:38
I just noticed that the daily pipeline (build check) failed as well since today, with the same error:
https://gitlab.com/timvisee/qr2term-rs/pipelines/73120925

**Comment by timvisee** [comment] 2019-07-26 10:46
I fixed this issue by updating a dependency.

This is included in `v0.1.3` of `qr2term-rs`. It should be released and usable on crates.io when this pipeline succeeds:  
https://gitlab.com/timvisee/qr2term-rs/pipelines/73124512

Assuming updating to `qr2term-rs v0.1.3`, I'll close this issue.

**Closed by timvisee** 2019-07-26 10:46 UTC

**Comment by cteters** [comment] 2019-07-30 03:27
This did the trick, thanks! Great cargo btw!
